### ISSUE TITLE
Fails to detect obvious art comission scam

### ISSUE THREAD

**Issue by NanashiTheNameless** [programmer2514/BetterDiscord-MessageScanAI#1]
![image](https://github.com/user-attachments/assets/ad448d99-62ae-48b8-a885-25d0a4d3ee9c)
this is a blatant commission scam example

For the record this was written to test, I do not believe there is an "ArtsCamelComms" and if there is it is not affiliated with them in any way shape or form

**Comment by programmer2514** [comment]
Thanks for the report!
This extension is relatively new, so I appreciate you taking the time to help me improve it :)

I have tweaked the request in v1.4.0 to improve both accuracy and security - let me know how the new model performs.
As always, false flags are going to happen, but it definitely shouldn't be flagging something that blatant as safe.

**Comment by NanashiTheNameless** [comment]
I'll test it rn, thanks for responding so fast!
